== Location Powers: Data Science Summit
//write text in as many clauses as necessary. Use one document or many, your choice!
The Location Powers: Data Science Summit organized by OGC was held on November 13 and 14, at Google, Mountain View, CA.  This OGC Tech Note was developed based on the Summit.  This Geospatial Data Science Tech Note captures the content of the Summit and provide a basis for further action in OGC and beyond.

The Location Powers Summit series brings together industry, research and government experts from across the globe into an interactive discussion that assess the current situation and produces recommendations for future technology innovations and standards development.   The Location Powers Summits are key to the technology innovation promoted by the Open Geospatial Consortium (OGC).
The Location Powers: Data Science Summit convened experts on data science, machine learning, artificial intelligence, cloud computing, remote sensing and GIS to provide a technology basis.  Participation by leaders in social sciences, business development and government policy will lead to recommendations that have meaningful outcomes from the geospatial data science developments.

The Location Powers: Data Science summit considered the explosive availability of data about nearly every aspect of human activity along with revolutionary advances in computing technologies is transforming geospatial data science.    The shift from data-scarce to data-rich environment comes from mobile devices, remote sensing and the Internet of Things. Nearly all of this data has components of location and time. Innovations in cloud computing and big data provides methods to perform data analytics at exceedingly large scale and speed. The development of intelligent systems using knowledge models and their impact on our insights and understanding will be focus of the Location Powers: Data Science Summit.

The Annex provides information about the summit including the agenda.
