== OGC activities on Geospatial Data Science

An objective of the Location Powers series is to identify OGC activities based on the outcomes and recommendations of the summit.  This Clause identifies potential OGC activities in three areas:

** OGC Program Activities
** External Coordination on Standards
** External coordination on R&D


=== OGC Program Activities

** Communicate the results of LP_DS Summit
*** Publish this White paper
*** Present the results of LP_DS to multiple venues
** OGC Standard Program
*** SP Working Groups: Discuss recommendations with WG chairs
*** Future Directions Sessions
** OGC Innovation Program
*** Monitor the related OGC Testbed 16 activities to update the concepts in this white paper
*** Recommend Testbed 17 work items on geospatial data science for consideration by sponsors
** Tech Trends:
*** update mindmap and priority trends
*** Plan for Location Powers 2020 summit based on results of LP_DS


External Coordination
Reach out to liaisons
Location Powers 2020


=== External Coordination on Standards

** Identify organizations focused on developing standards and best practices in Data Science
** Consider establishing liaisons with external organizations to develop geospatial data science.

=== External coordination on R&D

** Introduce Geospatial Data Science as a theme in the annual Apache Software Foundation (ASF) annual conference geospatial track.
** Participate in the NSF Geospatial Software Institute developments as they may happen in 2020 based on the incubator study concluded in 2019.
